;;; merlin-company-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from merlin-company.el

(autoload 'merlin-company-backend "merlin-company" "\


(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "merlin-company" '("merlin-company-"))

;;; End of scraped data

(provide 'merlin-company-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; merlin-company-autoloads.el ends here
