:PROPERTIES:
:ID:       D5A5CE83-1253-47D4-904E-AD73960FB818
:END:
#+title:Line, Algebra


A line in a [[id:32A7773E-6EFF-42D4-84F9-F6A0C41366D1][Vector space]] is defined via a point (technically a positional vector from the origin to that point), and a "direction vector".

\begin{align*}
L = A + \lambda\bf{x}
\end{align*}

where $\lambda \in \mathbb{R}$, $A \in \mathbb{R}^n$.

$A$ can be any point on the line, and $\bf{x}$ can be any vector that is parallel to the line.

Mention: [[id:F191098B-16E8-4CB3-B8EF-88EE6ED9E577][Colinear, Algebra]].

A line through two points $A$ and $B$ can therefore be defined as

\begin{align*}
L = \left\{ x \in \mathbb{R}^n |\, x = \vec{OA} + \lambda \vec{AB}, \lambda \in \mathbb{R} \right\}
\end{align*}

As $\vec{AB}$ is naturally a vector in the direction of the line, and $\vec{OA}$ is the offset vector to a point on the line.

It is fairly easy to obtain a vector representation from a cartesian one. If $y = 3x + 2$:

\begin{align*}
\begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} x \\ 3x + 2 \end{bmatrix}
= \begin{bmatrix} x + 0 \\ 3x + 2 \end{bmatrix}
= x \begin{bmatrix} 1 \\ 3 \end{bmatrix} + \begin{bmatrix} 0 \\ 2 \end{bmatrix}
= \begin{bmatrix} 0 \\ 2 \end{bmatrix} + \lambda \begin{bmatrix} 1 \\ 3 \end{bmatrix} 
\end{align*}

as required.

This of courses generalizes to multiple dimensions.








